theme: minima
title: "Quelques notes..."
timezone: Europe/Paris
description: "Quelques notes d'un développeur."
author: Benjamin POCHAT
email: "benjamin.pochat@gmail.com"
linkedin_username: benjamin-pochat-0a68495
github_username:  benjaminpochat
twitter_username: ""

show_drafts: true